# Form implementation generated from reading ui file 'landing_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtCore import pyqtSlot
from backend.Payment import benedicto_PaymentMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 456)
        MainWindow.setStyleSheet("background-color: rgb(98, 198, 147);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.benedicto_lbl_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.benedicto_lbl_name.setGeometry(QtCore.QRect(130, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_lbl_name.setFont(font)
        self.benedicto_lbl_name.setText("")
        self.benedicto_lbl_name.setObjectName("benedicto_lbl_name")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.benedicto_lbl_age = QtWidgets.QLabel(parent=self.centralwidget)
        self.benedicto_lbl_age.setGeometry(QtCore.QRect(70, 40, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_lbl_age.setFont(font)
        self.benedicto_lbl_age.setText("")
        self.benedicto_lbl_age.setObjectName("benedicto_lbl_age")
        self.benedicto_fries = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_fries.setGeometry(QtCore.QRect(50, 110, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_fries.setFont(font)
        self.benedicto_fries.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: #fff;")
        self.benedicto_fries.setObjectName("benedicto_fries")
        self.benedicto_milktea = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_milktea.setGeometry(QtCore.QRect(210, 110, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_milktea.setFont(font)
        self.benedicto_milktea.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: #fff;")
        self.benedicto_milktea.setObjectName("benedicto_milktea")
        self.benedicto_cheese = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_cheese.setGeometry(QtCore.QRect(20, 180, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_cheese.setFont(font)
        self.benedicto_cheese.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: #fff;")
        self.benedicto_cheese.setObjectName("benedicto_cheese")
        self.benedicto_soda = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_soda.setGeometry(QtCore.QRect(210, 180, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_soda.setFont(font)
        self.benedicto_soda.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: #fff;")
        self.benedicto_soda.setObjectName("benedicto_soda")
        self.benedicto_donut = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_donut.setGeometry(QtCore.QRect(50, 250, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_donut.setFont(font)
        self.benedicto_donut.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: #fff;")
        self.benedicto_donut.setObjectName("benedicto_donut")
        self.benedicto_icecream = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_icecream.setGeometry(QtCore.QRect(210, 250, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_icecream.setFont(font)
        self.benedicto_icecream.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: #fff;")
        self.benedicto_icecream.setObjectName("benedicto_icecream")
        self.benedicto_dc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_dc.setGeometry(QtCore.QRect(120, 330, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_dc.setFont(font)
        self.benedicto_dc.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"color: black;")
        self.benedicto_dc.setObjectName("benedicto_dc")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 400, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.benedicto_prview = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.benedicto_prview.setGeometry(QtCore.QRect(100, 400, 161, 31))
        self.benedicto_prview.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.benedicto_prview.setReadOnly(True)
        self.benedicto_prview.setObjectName("benedicto_prview")
        self.benedicto_pay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_pay.setGeometry(QtCore.QRect(280, 390, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_pay.setFont(font)
        self.benedicto_pay.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"color: black;")
        self.benedicto_pay.setObjectName("benedicto_pay")
        self.benedicto_tbl = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.benedicto_tbl.setGeometry(QtCore.QRect(410, 30, 241, 401))
        self.benedicto_tbl.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.benedicto_tbl.setObjectName("benedicto_tbl")
        self.benedicto_tbl.setColumnCount(2)
        self.benedicto_tbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.benedicto_tbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.benedicto_tbl.setHorizontalHeaderItem(1, item)
        self.benedicto_remove = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_remove.setGeometry(QtCore.QRect(670, 30, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_remove.setFont(font)
        self.benedicto_remove.setStyleSheet("background-color: red;\n"
"color: white;")
        self.benedicto_remove.setObjectName("benedicto_remove")
        self.benedicto_logout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_logout.setGeometry(QtCore.QRect(670, 390, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_logout.setFont(font)
        self.benedicto_logout.setStyleSheet("background-color: orange;\n"
"color: black;")
        self.benedicto_logout.setObjectName("benedicto_logout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome,"))
        self.label_2.setText(_translate("MainWindow", "Age: "))
        self.benedicto_fries.setText(_translate("MainWindow", "Fries - 30"))
        self.benedicto_milktea.setText(_translate("MainWindow", "Milktea - 60"))
        self.benedicto_cheese.setText(_translate("MainWindow", "Cheese Sticks - 25"))
        self.benedicto_soda.setText(_translate("MainWindow", "Soda - 20"))
        self.benedicto_donut.setText(_translate("MainWindow", "Donut - 20"))
        self.benedicto_icecream.setText(_translate("MainWindow", "Ice cream - 20"))
        self.benedicto_dc.setText(_translate("MainWindow", "Apply Discount"))
        self.label_3.setText(_translate("MainWindow", "Total:"))
        self.benedicto_pay.setText(_translate("MainWindow", "Pay"))
        item = self.benedicto_tbl.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Items"))
        item = self.benedicto_tbl.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Price"))
        self.benedicto_remove.setText(_translate("MainWindow", "Remove"))
        self.benedicto_logout.setText(_translate("MainWindow", "Logout"))

class benedicto_HomeMainWindow(QMainWindow, Ui_MainWindow):

    def __init__(self):
        from backend.Register import name, age
        super(benedicto_HomeMainWindow, self).__init__()
        self.setupUi(self)
        self.benedicto_lbl_name.setText(name)
        self.benedicto_lbl_age.setText(age)
        self.benedicto_dc.clicked.connect(self.discountbtn)
        self.products = [
            {"name": "Fries", "price": 30},
            {"name": "MilkTea", "price": 60},
            {"name": "Cheese Sticks", "price": 25},
            {"name": "Soda", "price": 20},
            {"name": "Donut", "price": 20},
            {"name": "Ice Cream", "price": 20}
        ]
    def discountbtn(self):
        from backend.Register import name, age

        if int(age) >= 60:
                discount = 0.20
                message = QMessageBox()
                message.setText('Discount Applied')
                message.exec()
                return discount
        else:
                message = QMessageBox()
                message.setText('Not Eligible for discount')
                message.exec()
                
    def add_product_buttons(self):
        buttons_layout = QHBoxLayout()

        for product in self.products:
            button = QPushButton(product["name"])
            button.clicked.connect(lambda _, p=product: self.add_product(p))
            buttons_layout.addWidget(button)

        self.layout.addLayout(buttons_layout)
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
