# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtCore import pyqtSlot
from backend.HomePage import benedicto_HomeMainWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 405)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 10, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.benedicto_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.benedicto_username.setGeometry(QtCore.QRect(150, 100, 171, 31))
        self.benedicto_username.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.benedicto_username.setObjectName("benedicto_username")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 100, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.benedicto_pass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.benedicto_pass.setGeometry(QtCore.QRect(150, 160, 171, 31))
        self.benedicto_pass.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.benedicto_pass.setObjectName("benedicto_pass")
        self.benedicto_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_login.setGeometry(QtCore.QRect(160, 270, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_login.setFont(font)
        self.benedicto_login.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.benedicto_login.setObjectName("benedicto_login")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.label_4.setText(_translate("MainWindow", "Username"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.benedicto_login.setText(_translate("MainWindow", "Login"))
        
class benedicto_LoginMainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(benedicto_LoginMainWindow, self).__init__()
        self.setupUi(self)
        self.benedicto_login.clicked.connect(self.loginButtonClicked)
    

    def loginButtonClicked (self):
        from backend.Register import benedicto_MainWindow, username, password
        
        if (username == self.benedicto_username.text()) and (password == self.benedicto_pass.text()):
            message = QMessageBox()
            message.setText('Login Success')
            message.exec()
            self.login_window = benedicto_HomeMainWindow()
            self.login_window.show()
            self.hide()
        else:
            message = QMessageBox()
            message.setText('Wrong Credentials')
            message.exec()
            
    
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = benedicto_LoginMainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
