# Form implementation generated from reading ui file 'payment_form.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtCore import pyqtSlot

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 269)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.benedicto_total = QtWidgets.QLabel(parent=self.centralwidget)
        self.benedicto_total.setGeometry(QtCore.QRect(170, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_total.setFont(font)
        self.benedicto_total.setText("")
        self.benedicto_total.setObjectName("benedicto_total")
        self.benedicto_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.benedicto_input.setGeometry(QtCore.QRect(50, 140, 221, 41))
        self.benedicto_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.benedicto_input.setObjectName("benedicto_input")
        self.benedicto_pay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_pay.setGeometry(QtCore.QRect(90, 210, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_pay.setFont(font)
        self.benedicto_pay.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"color: black;")
        self.benedicto_pay.setObjectName("benedicto_pay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Total Price:"))
        self.benedicto_pay.setText(_translate("MainWindow", "Pay"))

class benedicto_PaymentMainWindow(QMainWindow, Ui_MainWindow):
     def __init__(self):
        super(benedicto_PaymentMainWindow, self).__init__()
        self.setupUi(self)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
