# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtCore import pyqtSlot
from backend.Login import benedicto_LoginMainWindow

name = ''
age = ''
username = ''
password = ''

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(369, 470)
        MainWindow.setStyleSheet("background-color: rgb(195, 171, 255)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.benedicto_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.benedicto_name.setGeometry(QtCore.QRect(130, 80, 171, 31))
        self.benedicto_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.benedicto_name.setObjectName("benedicto_name")
        self.benedicto_age = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.benedicto_age.setGeometry(QtCore.QRect(130, 140, 171, 31))
        self.benedicto_age.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.benedicto_age.setObjectName("benedicto_age")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.benedicto_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.benedicto_username.setGeometry(QtCore.QRect(130, 200, 171, 31))
        self.benedicto_username.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.benedicto_username.setObjectName("benedicto_username")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.benedicto_pass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.benedicto_pass.setGeometry(QtCore.QRect(130, 260, 171, 31))
        self.benedicto_pass.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.benedicto_pass.setObjectName("benedicto_pass")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 260, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.benedicto_register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.benedicto_register.setGeometry(QtCore.QRect(150, 360, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.benedicto_register.setFont(font)
        self.benedicto_register.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.benedicto_register.setObjectName("benedicto_register")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign Up"))
        self.label.setText(_translate("MainWindow", "Sign Up"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Age"))
        self.label_4.setText(_translate("MainWindow", "Username"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.benedicto_register.setText(_translate("MainWindow", "NEXT"))
        
class benedicto_MainWindow(QMainWindow, Ui_MainWindow):
    
    def __init__(self):
        super(benedicto_MainWindow, self).__init__()
        self.setupUi(self)
        self.registeredClicked()
        
    def registeredClicked(self):
        self.benedicto_register.clicked.connect(self.onButtonClicked)

    def onButtonClicked(self):
        global name, age, username, password
        
        name = self.benedicto_name.text()
        age = self.benedicto_age.text()
        username = self.benedicto_username.text()
        password =  self.benedicto_pass.text()
        
        message = QMessageBox()
        
        if not (name and age and username and password):
            message.setText('All fields are required')
            message.exec()
            
        elif not age.isdigit() or int(age) <= 0:
            message_box = QMessageBox()
            message_box.setWindowTitle("Invalid Age")
            message_box.setText("Please enter a valid age (a positive number).")
            message_box.exec()
            
        else:
            
            message.setText('success')
            message.exec()
            self.login_window = benedicto_LoginMainWindow()
            self.login_window.show()
            self.hide()
            
       
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = benedicto_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
